"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
command_timeout = 2000

format = """
$os\
$directory\
$git_branch\
$git_status\
\n$character
"""

right_format = "$cmd_duration"

[git_status]
ahead = ""
behind = ""

[os]
disabled = false

[directory]
read_only = " 󰌾"

[git_branch]
symbol = " "

[os.symbols]
Alpine = " "
Arch = " "
Artix = " "
Debian = " "
Fedora = " "
Garuda = "󰛓 "
Gentoo = " "
Kali = " "
Linux = " "
Macos = " "
Mariner = " "
Mint = " "
NixOS = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
RockyLinux = " "
SUSE = " "
Ubuntu = " "
Void = " "
Windows = "󰍲 "

[cmd_duration]
min_time = 2000

[character]
success_symbol = "[❯](red)[❯](yellow)[❯](green)"
error_symbol = "[❯](red)[❯](yellow)[❯](green)"
vimcmd_symbol = '[❮](green)[❮](yellow)[❮](red)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
